import './globals.css';

export const metadata = {
  title: 'Al Hira Islamic Academy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="select-none">
      <body>{children}</body>
    </html>
  );
}
