import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './navbar';
import Footer from './footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Al Hira Islamic Academy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
